skip_commits:
  files:
    - appveyor.yml
    - README.md

branches:
  only:
    - refresh

version: 1.0.{build}

init:
  - ps: |
      if ($env:APPVEYOR_REPO_TAG -eq "true")
      {
        Update-AppveyorBuild -Version "$($env:APPVEYOR_REPO_TAG_NAME.TrimStart("v"))"
      }
      else
      {
        Update-AppveyorBuild -Version "0.0.$($env:APPVEYOR_BUILD_NUMBER)"
      }


configuration: Release

before_build:
  - nuget restore

build:
  verbosity: normal

artifacts:
  - path: PowerRedis2\bin\$(configuration)\*.dll

